
const currency_list = [
    { country: "Afghanistan", currency: "Afghani", code: "AFN" },
    { country: "Albania", currency: "Lek", code: "ALL" },
    { country: "Algeria", currency: "Algerian Dinar", code: "DZD" },
    { country: "American Samoa", currency: "US Dollar", code: "USD" },
    { country: "Andorra", currency: "Euro", code: "EUR" },
    { country: "Angola", currency: "Kwanza", code: "AOA" },
    { country: "Anguilla", currency: "East Caribbean Dollar", code: "XCD" },
    { country: "Antigua and Barbuda", currency: "East Caribbean Dollar", code: "XCD" },
    { country: "Argentina", currency: "Argentine Peso", code: "ARS" },
    { country: "Armenia", currency: "Armeniam Dram", code: "AMD" },
    { country: "Aruba", currency: "Aruban Florin", code: "AWG" },
    { country: "Australia", currency: "Australian Dollar", code: "AUD" },
    { country: "Austria", currency: "Euro", code: "EUR" },
    { country: "Azerbaijan", currency: "Azerbaijanian Manat", code: "AZN" },
    { country: "Bahamas", currency: "Bahamian Dollar", code: "BSD" },
    { country: "Bahrain", currency: "Bahraini Dinar", code: "BHD" },
    { country: "Bangladesh", currency: "Taka", code: "BDT" },
    { country: "Barbados", currency: "Barbados Dollar", code: "BBD" },
    { country: "Belarus", currency: "Belarusian Ruble", code: "BYN" },
    { country: "Belgium", currency: "Euro", code: "EUR" },
    { country: "Belize", currency: "Belize Dollar", code: "BZD" },
    { country: "Benin", currency: "CFA Franc (BCEAO)", code: "XOF" },
    { country: "Bermuda", currency: "Bermudian Dollar", code: "BMD" },
    { country: "Bhutan", currency: "Ngultrum", code: "BTN" },
    { country: "Bolivia (Plurinat.State)", currency: "Boliviano", code: "BOB" },
    { country: "Bonaire/S.Eustatius/Saba", currency: "US Dollar", code: "USD" },
    { country: "Bosnia and Herzegovina", currency: "Convertible Mark", code: "BAM" },
    { country: "Botswana", currency: "Pula", code: "BWP" },
    { country: "Brazil", currency: "Brazilian Real", code: "BRL" },
    { country: "British Indian Ocean Ter", currency: "US Dollar", code: "USD" },
    { country: "British Virgin Islands", currency: "US Dollar", code: "USD" },
    { country: "Brunei Darussalam", currency: "Brunei Dollar", code: "BND" },
    { country: "Bulgaria", currency: "Bulgarian Lev", code: "BGN" },
    { country: "Burkina Faso", currency: "CFA Franc (BCEAO)", code: "XOF" },
    { country: "Burundi", currency: "Burundi Franc", code: "BIF" },
    { country: "Cape Verde", currency: "Cabo Verde Escudo", code: "CVE" },
    { country: "Cambodia", currency: "Riel", code: "KHR" },
    { country: "Cameroon", currency: "CFA Franc (BEAC)", code: "XAF" },
    { country: "Canada", currency: "Canadian Dollar", code: "CAD" },
    { country: "Cayman Islands", currency: "Cayman Islands Dollar", code: "KYD" },
    { country: "Central African Republic", currency: "CFA Franc (BEAC)", code: "XAF" },
    { country: "Chad", currency: "CFA Franc (BEAC)", code: "XAF" },
    { country: "Channel Islands", currency: "Pound Sterling", code: "GBP" },
    { country: "Chile", currency: "Chilean Peso", code: "CLP" },
    { country: "China", currency: "Yuan Renminbi", code: "CNY" },
    { country: "China, Hong Kong SAR", currency: "Hong Kong Dollar", code: "HKD" },
    { country: "China, Macao SAR", currency: "Pataca", code: "MOP" },
    { country: "Taiwan Province of China", currency: "New Taiwan Dollar", code: "TWD" },
    { country: "Christmas Island", currency: "Australian Dollar", code: "AUD" },
    { country: "Cocos (Keeling) Islands", currency: "Australian Dollar", code: "AUD" },
    { country: "Colombia", currency: "Colombian Peso", code: "COP" },
    { country: "Comoros", currency: "Comoro Franc", code: "KMF" },
    { country: "Congo", currency: "CFA Franc (BEAC)", code: "XAF" },
    { country: "Congo, Dem. Rep. of the", currency: "Congolese Franc", code: "CDF" },
    { country: "Cook Islands", currency: "New Zealand Dollar", code: "NZD" },
    { country: "Costa Rica", currency: "Costa Rican Colón", code: "CRC" },
    { country: "Côte d'Ivoire", currency: "CFA Franc (BCEAO)", code: "XOF" },
    { country: "Croatia", currency: "Croatian Kuna", code: "HRK" },
    { country: "Cuba", currency: "Cuban Peso", code: "CUP" },
    { country: "Curaçao", currency: "Netherlands Antillian Guilder", code: "ANG" },
    { country: "Cyprus", currency: "Euro", code: "EUR" },
    { country: "Czechia", currency: "Czech Koruna", code: "CZK" },
    { country: "Denmark", currency: "Danish Krone", code: "DKK" },
    { country: "Djibouti", currency: "Djibouti Franc", code: "DJF" },
    { country: "Dominica", currency: "East Caribbean Dollar", code: "XCD" },
    { country: "Dominican Republic", currency: "Dominican Peso", code: "DOP" },
    { country: "Ecuador", currency: "US Dollar", code: "USD" },
    { country: "Egypt", currency: "Egyptian Pound", code: "EGP" },
    { country: "El Salvador", currency: "US Dollar", code: "USD" },
    { country: "Equatorial Guinea", currency: "CFA Franc (BEAC)", code: "XAF" },
    { country: "Eritrea", currency: "Nakfa", code: "ERN" },
    { country: "Estonia", currency: "Euro", code: "EUR" },
    { country: "Ethiopia", currency: "Ethiopian Birr", code: "ETB" },
    { country: "Falkland Is.(Malvinas)", currency: "Falkland Islands Pound", code: "FKP" },
    { country: "Faroe Islands", currency: "Danish Krone", code: "DKK" },
    { country: "Fiji, Republic of", currency: "Fiji Dollar", code: "FJD" },
    { country: "Finland", currency: "Euro", code: "EUR" },
    { country: "France", currency: "Euro", code: "EUR" },
    { country: "French Guiana", currency: "Euro", code: "EUR" },
    { country: "French Polynesia", currency: "CFP Franc", code: "XPF" },
    { country: "French Southern Terr", currency: "Euro", code: "EUR" },
    { country: "Gabon", currency: "CFA Franc (BEAC)", code: "XAF" },
    { country: "Gambia", currency: "Dalasi", code: "GMD" },
    { country: "Georgia", currency: "Lari", code: "GEL" },
    { country: "Germany", currency: "Euro", code: "EUR" },
    { country: "Ghana", currency: "Ghana Cedi", code: "GHS" },
    { country: "Gibraltar", currency: "Gibraltar Pound", code: "GIP" },
    { country: "Greece", currency: "Euro", code: "EUR" },
    { country: "Greenland", currency: "Danish Krone", code: "DKK" },
    { country: "Grenada", currency: "East Caribbean Dollar", code: "XCD" },
    { country: "Guadeloupe", currency: "Euro", code: "EUR" },
    { country: "Guam", currency: "US Dollar", code: "USD" },
    { country: "Guatemala", currency: "Quetzal", code: "GTQ" },
    { country: "Guernsey", currency: "Pound Sterling", code: "GBP" },
    { country: "Guinea", currency: "Guinea Franc", code: "GNF" },
    { country: "Guinea-Bissau", currency: "CFA Franc (BCEAO)", code: "XOF" },
    { country: "Guyana", currency: "Guyana Dollar", code: "GYD" },
    { country: "Haiti", currency: "Gourde", code: "HTG" },
    { country: "Honduras", currency: "Lempira", code: "HNL" },
    { country: "Hungary", currency: "Forint", code: "HUF" },
    { country: "Iceland", currency: "Iceland Króna", code: "ISK" },
    { country: "India", currency: "Indian Rupee", code: "INR" },
    { country: "Indonesia", currency: "Rupiah", code: "IDR" },
    { country: "Iran (Islamic Rep. of)", currency: "Iranian Rial", code: "IRR" },
    { country: "Iraq", currency: "Iraqi Dinar", code: "IQD" },
    { country: "Ireland", currency: "Euro", code: "EUR" },
    { country: "Isle of Man", currency: "Pound Sterling", code: "GBP" },
    { country: "Israel", currency: "New Israeli Sheqel", code: "ILS" },
    { country: "Italy", currency: "Euro", code: "EUR" },
    { country: "Jamaica", currency: "Jamaican Dollar", code: "JMD" },
    { country: "Japan", currency: "Yen", code: "JPY" },
    { country: "Jersey", currency: "Pound Sterling", code: "GBP" },
    { country: "Jordan", currency: "Jordanian Dinar", code: "JOD" },
    { country: "Kazakhstan", currency: "Tenge", code: "KZT" },
    { country: "Kenya", currency: "Kenyan Shilling", code: "KES" },
    { country: "Kiribati", currency: "Australian Dollar", code: "AUD" },
    { country: "Korea, Dem. People's Rep", currency: "North Korean Won", code: "KPW" },
    { country: "Korea, Republic of", currency: "Won", code: "KRW" },
    { country: "Kuwait", currency: "Kuwaiti Dinar", code: "KWD" },
    { country: "Kyrgyzstan", currency: "Som", code: "KGS" },
    { country: "Lao People's Dem. Rep.", currency: "Kip", code: "LAK" },
    { country: "Latvia", currency: "Euro", code: "EUR" },
    { country: "Lebanon", currency: "Lebanese Pound", code: "LBP" },
    { country: "Lesotho", currency: "Loti", code: "LSL" },
    { country: "Liberia", currency: "Liberian Dollar", code: "LRD" },
    { country: "Libya", currency: "Libyan Dinar", code: "LYD" },
    { country: "Liechtenstein", currency: "Swiss Franc", code: "CHF" },
    { country: "Lithuania", currency: "Euro", code: "EUR" },
    { country: "Luxembourg", currency: "Euro", code: "EUR" },
    { country: "Macedonia, Fmr Yug Rp of", currency: "Denar", code: "MKD" },
    { country: "Madagascar", currency: "Malagasy Ariary", code: "MGA" },
    { country: "Malawi", currency: "Malawi Kwacha", code: "MWK" },
    { country: "Malaysia", currency: "Malaysian Ringgit", code: "MYR" },
    { country: "Maldives", currency: "Rufiyaa", code: "MVR" },
    { country: "Mali", currency: "CFA Franc (BCEAO)", code: "XOF" },
    { country: "Malta", currency: "Euro", code: "EUR" },
    { country: "Marshall Islands", currency: "US Dollar", code: "USD" },
    { country: "Martinique", currency: "Euro", code: "EUR" },
    { country: "Mauritania", currency: "Ouguiya", code: "MRO" },
    { country: "Mauritius", currency: "Mauritius Rupee", code: "MUR" },
    { country: "Mayotte", currency: "Euro", code: "EUR" },
    { country: "Mexico", currency: "Mexican Peso", code: "MXN" },
    { country: "Micronesia,Fed.States of", currency: "US Dollar", code: "USD" },
    { country: "Moldova, Republic of", currency: "Moldovan Leu", code: "MDL" },
    { country: "Mongolia", currency: "Tugrik", code: "MNT" },
    { country: "Montenegro", currency: "Euro", code: "EUR" },
    { country: "Montserrat", currency: "East Caribbean Dollar", code: "XCD" },
    { country: "Morocco", currency: "Moroccan Dirham", code: "MAD" },
    { country: "Mozambique", currency: "Metical", code: "MZN" },
    { country: "Myanmar", currency: "Kyat", code: "MMK" },
    { country: "Namibia", currency: "Namibian Dollar", code: "NAD" },
    { country: "Nauru", currency: "Australian Dollar", code: "AUD" },
    { country: "Nepal", currency: "Nepalese Rupee", code: "NPR" },
    { country: "Netherlands", currency: "Euro", code: "EUR" },
    { country: "New Caledonia", currency: "CFP Franc", code: "XPF" },
    { country: "New Zealand", currency: "New Zealand Dollar", code: "NZD" },
    { country: "Nicaragua", currency: "Córdoba Oro", code: "NIO" },
    { country: "Niger", currency: "CFA Franc (BCEAO)", code: "XOF" },
    { country: "Nigeria", currency: "Naira", code: "NGN" },
    { country: "Niue", currency: "New Zealand Dollar", code: "NZD" },
    { country: "Northern Mariana Is.", currency: "US Dollar", code: "USD" },
    { country: "Norway", currency: "Norwegian Krone", code: "NOK" },
    { country: "Oman", currency: "Rial Omani", code: "OMR" },
    { country: "Pakistan", currency: "Pakistan Rupee", code: "PKR" },
    { country: "Palau", currency: "US Dollar", code: "USD" },
    { country: "Panama", currency: "Balboa", code: "PAB" },
    { country: "Papua New Guinea", currency: "Kina", code: "PGK" },
    { country: "Paraguay", currency: "Guaraní", code: "PYG" },
    { country: "Peru", currency: "Sol", code: "PEN" },
    { country: "Philippines", currency: "Philippine Peso", code: "PHP" },
    { country: "Pitcairn Islands", currency: "New Zealand Dollar", code: "NZD" },
    { country: "Poland", currency: "Zloty", code: "PLN" },
    { country: "Portugal", currency: "Euro", code: "EUR" },
    { country: "Puerto Rico", currency: "US Dollar", code: "USD" },
    { country: "Qatar", currency: "Qatari Rial", code: "QAR" },
    { country: "Réunion", currency: "Euro", code: "EUR" },
    { country: "Romania", currency: "Romanian Leu", code: "RON" },
    { country: "Russian Federation", currency: "Russian Ruble", code: "RUB" },
    { country: "Rwanda", currency: "Rwanda Franc", code: "RWF" },
    { country: "Saint Barthélemy", currency: "Euro", code: "EUR" },
    { country: "Saint Helena", currency: "Saint Helena Pound", code: "SHP" },
    { country: "Saint Kitts and Nevis", currency: "East Caribbean Dollar", code: "XCD" },
    { country: "Saint Lucia", currency: "East Caribbean Dollar", code: "XCD" },
    { country: "Saint-Martin", currency: "Euro", code: "EUR" },
    { country: "St. Pierre and Miquelon", currency: "Euro", code: "EUR" },
    { country: "Saint Vincent/Grenadines", currency: "East Caribbean Dollar", code: "XCD" },
    { country: "Samoa", currency: "Tala", code: "WST" },
    { country: "Sao Tome and Principe", currency: "Dobra", code: "STD" },
    { country: "Saudi Arabia", currency: "Saudi Riyal", code: "SAR" },
    { country: "Senegal", currency: "CFA Franc (BCEAO)", code: "XOF" },
    { country: "Serbia", currency: "Serbian Dinar", code: "RSD" },
    { country: "Seychelles", currency: "Seychelles Rupee", code: "SCR" },
    { country: "Sierra Leone", currency: "Leone", code: "SLL" },
    { country: "Singapore", currency: "Singapore Dollar", code: "SGD" },
    { country: "Sint Maarten", currency: "Netherlands Antillian Guilder", code: "ANG" },
    { country: "Slovakia", currency: "Euro", code: "EUR" },
    { country: "Slovenia", currency: "Euro", code: "EUR" },
    { country: "Solomon Islands", currency: "Solomon Islands Dollar", code: "SBD" },
    { country: "Somalia", currency: "Somali Shilling", code: "SOS" },
    { country: "South Africa", currency: "Rand", code: "ZAR" },
    { country: "South Sudan", currency: "South Sudanese Pound", code: "SSP" },
    { country: "Spain", currency: "Euro", code: "EUR" },
    { country: "Sri Lanka", currency: "Sri Lanka Rupee", code: "LKR" },
    { country: "Sudan", currency: "Sudanese Pound", code: "SDG" },
    { country: "Suriname", currency: "Suriname Dollar", code: "SRD" },
    { country: "Swaziland", currency: "Lilangeni", code: "SZL" },
    { country: "Sweden", currency: "Swedish Krona", code: "SEK" },
    { country: "Switzerland", currency: "Swiss Franc", code: "CHF" },
    { country: "Syrian Arab Republic", currency: "Syrian Pound", code: "SYP" },
    { country: "Tajikistan", currency: "Somoni", code: "TJS" },
    { country: "Tanzania, United Rep. of", currency: "Tanzanian Shilling", code: "TZS" },
    { country: "Thailand", currency: "Baht", code: "THB" },
    { country: "Timor-Leste", currency: "US Dollar", code: "USD" },
    { country: "Togo", currency: "CFA Franc (BCEAO)", code: "XOF" },
    { country: "Tokelau", currency: "New Zealand Dollar", code: "NZD" },
    { country: "Tonga", currency: "Pa'anga", code: "TOP" },
    { country: "Trinidad and Tobago", currency: "Trinidad and Tobago Dollar", code: "TTD" },
    { country: "Tunisia", currency: "Tunisian Dinar", code: "TND" },
    { country: "Turkey", currency: "Turkish Lira", code: "TRY" },
    { country: "Turkmenistan", currency: "Turkmenistan New Manat", code: "TMT" },
    { country: "Turks and Caicos Is.", currency: "US Dollar", code: "USD" },
    { country: "Tuvalu", currency: "Australian Dollar", code: "AUD" },
    { country: "Uganda", currency: "Uganda Shilling", code: "UGX" },
    { country: "Ukraine", currency: "Hryvnia", code: "UAH" },
    { country: "United Arab Emirates", currency: "UAE Dirham", code: "AED" },
    { country: "United Kingdom", currency: "Pound Sterling", code: "GBP" },
    { country: "United States of America", currency: "US Dollar", code: "USD" },
    { country: "US Virgin Islands", currency: "US Dollar", code: "USD" },
    { country: "Uruguay", currency: "Peso Uruguayo", code: "UYU" },
    { country: "Uzbekistan", currency: "Uzbekistan Sum", code: "UZS" },
    { country: "Vanuatu", currency: "Vatu", code: "VUV" },
    { country: "Venezuela, Boliv Rep of", currency: "Bolívar", code: "VEF" },
    { country: "Viet Nam", currency: "Dong", code: "VND" },
    { country: "Wallis and Futuna Is.", currency: "CFP Franc", code: "XPF" },
    { country: "Western Sahara", currency: "Moroccan Dirham", code: "MAD" },
    { country: "Yemen", currency: "Yemeni Rial", code: "YER" },
    { country: "Zambia", currency: "Zambian Kwacha", code: "ZMW" },
    { country: "Zimbabwe", currency: "Zimbabwe Dollar", code: "ZWL" }
]



export default currency_list;