const weSupportedCountries = [
    { id: 112, name: "Afghanistan" },
    { id: 110, name: "Algeria" },
    { id: 91, name: "Andorra" },
    { id: 57, name: "Angola" },
    { id: 78, name: "Argentina" },
    { id: 93, name: "Armenia" },
    { id: 103, name: "Aruba" },
    { id: 149, name: "Australia" },
    { id: 114, name: "Austria" },
    { id: 104, name: "Azerbaijan" },
    { id: 32, name: "Bahrain" },
    { id: 75, name: "Bangladesh" },
    { id: 134, name: "Belgium" },
    { id: 39, name: "Belize" },
    { id: 63, name: "Benin" },
    { id: 4, name: "Bhutan" },
    { id: 31, name: "Bolivia" },
    { id: 143, name: "Bosnia and Herzegovina" },
    { id: 58, name: "Botswana" },
    { id: 107, name: "Brazil" },
    { id: 64, name: "Burkina Faso" },
    { id: 59, name: "Burundi" },
    { id: 146, name: "Cambodia" },
    { id: 5, name: "Cameroon" },
    { id: 2, name: "Canada" },
    { id: 111, name: "Cape Verde" },
    { id: 147, name: "Chad" },
    { id: 150, name: "Christmas Island" },
    { id: 51, name: "Comoros" },
    { id: 135, name: "Congo" },
    { id: 70, name: "Cook Islands" },
    { id: 13, name: "Costa Rica" },
    { id: 141, name: "Croatia" },
    { id: 14, name: "Cuba" },
    { id: 72, name: "Cyprus" },
    { id: 124, name: "Czech Republic" },
    { id: 136, name: "Democratic Republic" },
    { id: 49, name: "Djibouti" },
    { id: 35, name: "East Timor" },
    { id: 86, name: "Ecuador" },
    { id: 29, name: "El Salvador" },
    { id: 102, name: "Equatorial Guinea" },
    { id: 52, name: "Eritrea" },
    { id: 92, name: "Estonia" },
    { id: 137, name: "Faroe Islands" },
    { id: 79, name: "Finland" },
    { id: 77, name: "France" },
    { id: 87, name: "French Polynesia" },
    { id: 53, name: "Gabon" },
    { id: 156, name: "Gambia" },
    { id: 68, name: "Georgia" },
    { id: 148, name: "Germany" },
    { id: 157, name: "Ghana" },
    { id: 128, name: "Gibraltar" },
    { id: 142, name: "Greece" },
    { id: 15, name: "Greenland" },
    { id: 73, name: "Guatemala" },
    { id: 66, name: "Guinea" },
    { id: 105, name: "Guyana" },
    { id: 16, name: "Haiti" },
    { id: 74, name: "Hong Kong" },
    { id: 151, name: "Iceland" },
    { id: 84, name: "IndiaCanada" },
    { id: 0, name: "India" },
    { id: 76, name: "Iraq" },
    { id: 1, name: "Ireland" },
    { id: 90, name: "Israel" },
    { id: 167, name: "Italy" },
    { id: 65, name: "Ivory Coast" },
    { id: 67, name: "Japan" },
    { id: 83, name: "Jordan" },
    { id: 71, name: "Kiribati" },
    { id: 109, name: "Korea(South)" },
    { id: 139, name: "Kyrgyzstan" },
    { id: 140, name: "Laos" },
    { id: 81, name: "Lesotho" },
    { id: 54, name: "Liberia" },
    { id: 60, name: "Libya" },
    { id: 118, name: "Liechtenstein" },
    { id: 170, name: "Luxembourg" },
    { id: 36, name: "Macau" },
    { id: 47, name: "Malawi" },
    { id: 123, name: "Malaysia" },
    { id: 44, name: "Mali" },
    { id: 117, name: "Malta" },
    { id: 45, name: "Mauritania" },
    { id: 61, name: "Mayotte" },
    { id: 96, name: "Mexico" },
    { id: 120, name: "Micronesia" },
    { id: 153, name: "Moldova" },
    { id: 106, name: "Mongolia" },
    { id: 129, name: "Mozambique" },
    { id: 125, name: "Namibia" },
    { id: 164, name: "Nauru" },
    { id: 169, name: "Netherlands" },
    { id: 42, name: "New Caledonia" },
    { id: 97, name: "NewZealand" },
    { id: 46, name: "Niger" },
    { id: 33, name: "Norway" },
    { id: 27, name: "Palau" },
    { id: 30, name: "Panama" },
    { id: 37, name: "Papua New Guinea" },
    { id: 99, name: "Paraguay" },
    { id: 98, name: "Pitcairn" },
    { id: 113, name: "Poland" },
    { id: 115, name: "Portugal" },
    { id: 62, name: "Reunion" },
    { id: 12, name: "Romania" },
    { id: 130, name: "Rwanda" },
    { id: 82, name: "Samoa" },
    { id: 116, name: "San Marino" },
    { id: 121, name: "Sao Tome and Principe" },
    { id: 80, name: "Senegal" },
    { id: 50, name: "Seychelles" },
    { id: 55, name: "Sierra Leone" },
    { id: 154, name: "Slovakia" },
    { id: 131, name: "Somalia" },
    { id: 48, name: "South Africa" },
    { id: 108, name: "South Korea" },
    { id: 163, name: "South Sudan" },
    { id: 89, name: "Spain" },
    { id: 160, name: "Sudan" },
    { id: 28, name: "Swaziland" },
    { id: 34, name: "Switzerland" },
    { id: 69, name: "Syria" },
    { id: 100, name: "Taiwan" },
    { id: 43, name: "Tajikistan" },
    { id: 56, name: "Togo" },
    { id: 132, name: "Tonga" },
    { id: 88, name: "Tunisia" },
    { id: 158, name: "Uganda" },
    { id: 155, name: "Ukraine" },
    { id: 3, name: "United States" },
    { id: 101, name: "Uruguay" },
    { id: 122, name: "Vanuatu" },
    { id: 168, name: "Vietnam" },
    { id: 159, name: "Yemen" },
    { id: 133, name: "Zambia" }
]
export default weSupportedCountries