const url = `https://paycio.nyc3.cdn.digitaloceanspaces.com/website/images/webp`;
const mediakiturl = `https://paycio.nyc3.cdn.digitaloceanspaces.com/website/images`;
export const logos = {

  crypto_fiatsolutions : `${url}/crypto-and-fiatsolutions.webp`,
  inclusive_ecosystem : `${url}/inclusive-ecosystem.webp`,
  privavy_policy : `${url}/privacy-policy.webp`,
  terms_conditions : `${url}/terms-and-conditions.webp`,
  ucpi_system : `${url}/ucpi-system.webp`,
  ucpi : `${url}/ucpi.webp`,
  api_integration : `${url}/api-integration.webp`,
  governments_banks : `${url}/governments-and-banks.webp`,
  bankinginclusion : `${url}/financial-inclusion.svg`,
  crossborder_payments : `/images/cross-border.png`,
  fiat_support : `/images/multi-chain.png`,
  traditional_payment_systems : `/images/impact-system.png`,
  innovation_growth : `${url}/innovation-and-growth.svg`,
  regulatory_oversight : `${url}/regulatory-oversight.svg`,
  taxrevenue : `${url}/tax-revenue.svg`,
  financialinclusion : `${url}/financial-inclusion.svg`,
  kyc: `${url}/kyc.mp4`,
  kyc1: `${url}/real-time-monitoring.webp`,
  kyc2: `${url}/privacy-protection.webp`,
  kyc3: `${url}/advanced-data-protection.webp`,
  kyc4: `${url}/security-design.webp`,
  kycb: `${url}/kycb.mp4`,
  secure : `${url}/secure.webp`,
  pc: `${url}/paycio-rounded-logo.webp`,
  offline_pay: `${url}/offline_pay.mp4`,
  offline_mp4: `${url}/offline_mp4.mp4`,
  joinpaycio: `${url}/join-the-paycio.webp`,
  competative_fee: `${url}/competative-fee.svg`,
  needmobilenumber: `${url}/need-mobile-number.svg`,
  topnotchinnovation: `${url}/top-notch-innovations.svg`,
  p2puserprofile: `${url}/p2p-user-profile.webp`,
  p2pbuyorder: `${url}/p2p-buy-order.webp`, 
  p2pbuytrades: `${url}/p2p-buy-trades.webp` ,
  p2pswaptrades: `${url}/p2p-swap-trades.webp` ,
  p2ptradedetails: `${url}/p2p-trade-details.webp`,
  Kycchain: `${url}/Kycchain.webp`,
  tirupathicapital: `${url}/partners/tirupathi-capital.webp`,
  kyclevel1: `${url}/kyclevel1.svg`,
  kyclevel2: `${url}/kyclevel2.png`,
  kyclevel3: `${url}/kyclevel3.png`,
  timer: `${url}/timer.webp`,
  dollar: `${url}/dollar.webp `,
  checkmark: `${url}/checkmark.svg`,
  ucpi_home: `${url}/ucpi.webp`,
  playcircle: `${url}/play-circle.svg`,
  web3banner: `${url}/extra/web3-banner.jpg`,
  halfstrip: `${url}/half-strip.svg`,
  globe_animation: `${url}/globe_animation.gif`,
  mobilealt: `${url}/mobile-alt.svg`,
  ioslock: `${url}/ios-lock.svg`,
  checkuser: `${url}/check-user.svg`,
  handshake: `${url}/referring-friends-paycio.webp`,
  earnrewards: `${url}/earn-rewards.webp`,
  refprogram: `${url}/referral-program.webp`,
  inviteearn: `${url}/invite-and-earn.webp`,
  depositref: `${url}/deposit-rewards.webp`,
  verify: `${url}/verify.svg`,
  identification: `${url}/identification.svg`,
  referbanner1: `${url}/paycio-thankyou-coupons.webp`,
  referbanner2: `${url}/paycio-fabfive-coupons.webp`,
  appstore: `${url}/app-store.webp`,
  playstore: `${url}/play-store.webp`,
  paycio_login: `${url}/paycio-login.webp`,
  transaction_info: `${url}/transaction-info.webp`,
  transaction_fillters: `${url}/transaction-fillters.webp`,
  basiclevelkyc : `${url}/basic-level-kyc.svg`,
  standardlevelkyc : `${url}/standard-level-kycC.svg`,
  enhancedlevelkyc : `${url}/enhanced-level-kyc.svg`,
  supportedcountries : `${url}/supported-countries.webp`,
  pyctransactions : `${url}/pyc-transactions.webp`,

  media_productimages : `${mediakiturl}/mediakit/product-images.png`,
  media_typefaces : `${mediakiturl}/mediakit/typeface.png`,
  media_brandstyleguide: `${mediakiturl}/mediakit/brand-style-guide.png`,
  media_colors : `${mediakiturl}/mediakit/colors.png`,

  media_dashboard1: `${mediakiturl}/mediakit/product-images/dashboard-1.jpg `,
  media_dashboard2:  `${mediakiturl}/mediakit/product-images/dashboard-2.jpg `,
  media_dashboard3: `${mediakiturl}/mediakit/product-images/dashboard-3.jpg`, 
  media_swap: `${mediakiturl}/mediakit/product-images/swap.jpg `,
  media_wallet: `${mediakiturl}/mediakit/product-images/wallet.jpg `,
  media_withdraw: `${mediakiturl}/mediakit/product-images/withdraw.jpg`,

  paycio_logo_black: `${mediakiturl}/mediakit/png/paycio-logo-black.png`,
  paycio_logo_color_rounded: `${mediakiturl}/mediakit/png/paycio-logo-color-rounded.png`,
  paycio_logo_white_rounded: `${mediakiturl}/mediakit/png/paycio-logo-white-rounded.png`,
  paycio_logo_white: `${mediakiturl}/mediakit/png/paycio-logo-white.png`,
  rounded_paycio_black: `${mediakiturl}/mediakit/png/rounded-paycio-black.png`,
  rounded_paycio_white: `${mediakiturl}/mediakit/png/rounded-paycio-white.png`,
  rounded_paycio: `${mediakiturl}/mediakit/png/rounded-logo.png`,

  paycio_logo_black_svg: `${mediakiturl}/mediakit/svg/paycio-logo-black.svg`,
  paycio_logo_color_rounded_svg: `${mediakiturl}/mediakit/svg/paycio-logo-color-rounded.svg`,
  paycio_logo_white_rounded_svg: `${mediakiturl}/mediakit/svg/paycio-logo-white-rounded.svg`,
  paycio_logo_white_svg: `${mediakiturl}/mediakit/svg/paycio-logo-white.svg`,
  rounded_paycio_black_svg: `${mediakiturl}/mediakit/svg/rounded-paycio-black.svg`,
  rounded_paycio_white_svg: `${mediakiturl}/mediakit/svg/rounded-paycio-white.svg`,
  rounded_paycio_svg: `${mediakiturl}/mediakit/svg/rounded-logo.svg`,

  paycio_logo_black_hdpng: `${mediakiturl}/mediakit/hd-images/paycio-logo-black.png`,
  paycio_logo_color_rounded_hdpng: `${mediakiturl}/mediakit/hd-images/paycio-logo-color-rounded.png`,
  paycio_logo_white_rounded_hdpng: `${mediakiturl}/mediakit/hd-images/paycio-logo-white-rounded.png`,
  paycio_logo_white_hdpng: `${mediakiturl}/mediakit/hd-images/paycio-logo-white.png`,
  rounded_paycio_black_hdpng: `${mediakiturl}/mediakit/hd-images/rounded-paycio-black.png`,
  rounded_paycio_white_hdpng: `${mediakiturl}/mediakit/hd-images/rounded-paycio-white.png`,
  rounded_paycio_hdpng: `${mediakiturl}/mediakit/hd-images/rounded-logo.png`,

  tencent: `${url}/partners/tencent.webp`,
  nvidia: `${url}/partners/nvidia.webp`,
  astra: `${url}/partners/astra.webp`,
  kycchain: `${url}/partners/kycchain.webp`,
  googleDev: `${url}/partners/google-dev.webp`,
  quillAudit: `${url}/partners/quillaudit.webp`,
  mcbdao: `${url}/partners/mcbdao.webp`,
  payonramp: `${url}/partners/payonramp.webp`,
  skor: `${url}/partners/skor.webp`,
  securedApp: `${url}/partners/securedapp.webp`,
  seapen: `${url}/partners/seapen.webp`,
  coinearth: `${url}/partners/coinearth.webp`,
  tirupathiCapital: `${url}/partners/tirupathicapital.webp`,
  ennobleIp: `${url}/partners/ennobleip.webp`,
  cyl: `${url}/partners/cyl.webp`,
  assetHomez: `${url}/partners/assethomez.webp`,
  codeate: `${url}/partners/codeate.webp`,
  codeit: `${url}/partners/codeit.webp`,
  devboard: `${url}/partners/devboard.webp`,
  ecell: `${url}/partners/ecell.webp`,
  geekNation: `${url}/partners/geeknation.webp`,
  hackWithIndia: `${url}/partners/hackwithindia.webp`,
  indianHackingLeague: `${url}/partners/indianhackingleague.webp`,
  inovact: `${url}/partners/inovact.webp`,
  sotechInc: `${url}/partners/sotechinc.webp`,
  web3Aligarh: `${url}/partners/web3aligargh.webp`,
  idc: `${url}/partners/idc.webp`,
  itc: `${url}/partners/itc.webp`,
  monitok: `${url}/partners/monitok.webp`,
  threeWayStudio: `${url}/partners/three-way-studio.webp`,
  vitBlockchainCommunity: `${url}/partners/vitblockchaincommunity.webp`,
  walletHunter: `${url}/partners/wallethunter.webp`,
  web3InnovatorsNexus: `${url}/partners/web3-innovators-nexus.webp`,
  aetherium: `${url}/partners/aetherium.webp`,
  alertCode: `${url}/partners/alertcode.webp`,
  avinyaLabs: `${url}/partners/avinya-labs.webp`,
  befikraCommunity: `${url}/partners/befikra-community.webp`,
  buidlxHackathon: `${url}/partners/buidlx-hackathon.webp`,
  codeLnBlogs: `${url}/partners/codelnblogs.webp`,
  decentraClasses: `${url}/partners/decentra-classes.webp`,
  devGrowth: `${url}/partners/devgrowth.webp`,
  blockon: `/images/block-on.png`,
  unicoin: `/images/unicoin.png`,
}

